#goal definition
geometry_msgs/Pose final_point
float32 min_distance
bool backwards
float32 back_distance
float32 forward_velocity
bool use_smooth_map
---
#result definition
geometry_msgs/Pose current_point
---
#feedback
geometry_msgs/Pose current_point
